### PR TITLE
Fix AttributeError: module 'pyscf.pbc.df.ft_ao' has no attribute '_ft_aopair_kpts'

### PR DESCRIPTION
**Pull request by MarcoBarroca**
This fixes issue #19 and is necessary because of [this commit ](https://github.com/pyscf/pyscf/commit/90fe896504e69490d662425d89768dd2fd882973#diff-eb0624d8f70ec044bea2222a0c71f12d503c1e6a792171c5476faff8c8433905L51) to PySCF.

### CODE REVIEW

**Comment by MarcoBarroca** [comment]
I thought I had a more up-to-date version of PySCF. Turns out this will only work up to version 2.0.1 of PySCF

@sunqm Has this plugin been completely abandoned? I wanted to use PySCF with MPI but seems like updating this to version 2.3.0 would be a lot of work.

**Comment by sunqm** [comment]
This repo is not abandoned. The pbc.df module in pyscf is changed so much since v2.0. Not enough resource can be put in this repo regarding those changes.

**Comment by sunqm** [comment]
I will merge your PR. I guess it should make the FFTDF class working with MPI. The GDF code will fail if working with pyscf-2.3
